apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hundred
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/jooakar/nixos-config.git
    targetRevision: main
    path: cluster/apps/hundred
  destination:
    server: https://kubernetes.default.svc
    namespace: hundred
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: hundred
      jsonPointers:
        - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
